### ISSUE TITLE
about decoder

### ISSUE THREAD

**Issue by breadbread1984** [int8/VAE_tensorflow#1]
I read your code and found that you decode the face with the sigmoid of the last layer's output rather than a Bayesian inference procedure. Why do you implement this way?

**Comment by int8** [comment]
The output of the last deconv layer is 3-channel image because it is desired to be similar to the corresponding input image (while training) - the input is normalized to be within (0,1) [each pixel], I used sigmoid to enforce (0,1) range on the output too, does that help you ?

**Comment by breadbread1984** [comment]
Thx for prompt reply
