### ISSUE TITLE
the arg --output--dir can't work correctly 

### ISSUE THREAD

**Issue by freebooterish** [int8/VAE_tensorflow#3]
Hi,
      Thank you very much for your outstanding project.
      I test the command "python vae.py sample --output--dir trump trump-model, it show some errors:

** File "vae.py", line 50, in <module>
    imsave(args.output_dir + str(k) + '_' + str(i) + '.png', samples[i][0,:,:,:])
AttributeError: 'Namespace' object has no attribute 'output'**

     So, I check the file:common/vae_args.py:
**sample_parser.add_argument('--output--dir', help='Output dir where png files are stored ', type=str, default='samples
/', metavar='')
**
   the output dir is mismatch in two file: one is "output_dir" and another is "output--dir", 
   Is it a small mistake?

   Best regards.

**Comment by int8** [comment]
thanks for your interest in my tiny project :) 

you're right, that is a small typo, I will fix it shortly
