### ISSUE TITLE
How to use FeatureExtraction utility from OpenFace

### ISSUE THREAD

**Issue by freebooterish** [int8/VAE_tensorflow#4]
Hi,In your [http://int8.io/variational-autoencoder-in-tensorflow/]:
Then I used FeatureExtraction utility from OpenFace to get set of images of faces of the actor

Could you give a hint how to use "FeatureExtraction utility" from OpenFace?
thank you.

**Comment by int8** [comment]
I followed the instructions from here: https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments
