### ISSUE TITLE
No module named 'Image'

### ISSUE THREAD

**Issue by fernande2000** [int8/VAE_tensorflow#6]

**Comment by int8** [comment]
I can see you closed it - can you please share what your original problem was?

**Comment by fernande2000** [comment]
Hi, sorry about that.  I was having problems with the Image module, it complained that it did not exist. I modified one of the files to load it after another module that I think was the one supposed to have it, and it stopped complaining. I do not know if it is the same Image module you intended though, because I still could not run the program because I have troubles with my computer (most likely will have to replace it)

**Comment by int8** [comment]
Ok :) Good luck with your new setup then!
